server:
  port: 9090
  compression: 
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/erp_laozhang?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: alvin
#    url: jdbc:mysql://localhost:3306/keep?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: gzz123
#server: 
#    ssl: 
#      key-store: classpath:keystore.p12
#      key-store-password: 38967098gzz
#      keyStoreType: PKCS12
#      keyAlias: jetty
gen:
  project:
    outdir: D:/pro_dir
    datadir: D:/pro_data
    templatedir: D:/pro_temp_data